# ===================================================================
#  CONFIGURAÇÃO DO BANCO DE DADOS (Docker Network)
# ===================================================================
# 'postgresdb' é o nome do serviço definido no docker-compose.yml
spring.datasource.url=jdbc:postgresql://postgresdb:5432/course
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================================================
#  JPA / HIBERNATE
# ===================================================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=false