spring.application.name=course
spring.profiles.active=docker
spring.jpa.open-in-view=true

# =======================================
#  CONFIGURAÇÕES DO MYSQL (CORRIGIDAS)
# =======================================

# URL de conexão com o Timezone (UTC)
spring.datasource.url=jdbc:mysql://localhost:3306/course_db?serverTimezone=UTC

# Credenciais
spring.datasource.username=root
spring.datasource.password=root

# Dialeto
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# 'update': Cria/atualiza as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update

# Mostra o SQL no console
spring.jpa.show-sql=true