# ==============================
# PROFILE: dev (PostgreSQL local)
# ==============================

# --- Conexão PostgreSQL local ---
spring.datasource.url=jdbc:postgresql://localhost:5432/course
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=create
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Desativa H2 neste profile
spring.h2.console.enabled=false
